# Run 'bundle exec jekyll serve' again if you change this file.

# Site settings
title: Home
author: Phil Garner
# email: Phil.Garner@idiap.ch
description: >
  These pages contain information about my work, publications and software.

# These stop it being portable.  Better to leave it at github.
# baseurl: "~pgarner"
# url: "http://idiap.ch"
twitter_username: philipngarner
github_username:  pgarner

# Build settings
markdown: kramdown
theme: minima

# Minima date format; refer to http://shopify.github.io/liquid/filters/date/
minima:
  date_format: "%b %-d, %Y"

# Specific pages that should appear in the header; order is respected.
header_pages:
 - group.md
 - positions.md
 - projects.md
 - talks.md
 - appendices.md
 - blog.md

# Collections of things.
# Flatten the publications so the css path works with baseurls
collections:
 pubs:
   permalink: /:name
   output: true
 appendices:
   output: true
 ssp-course:
   output: true

# Exclude from processing.
exclude:
 - Gemfile
 - Gemfile.lock
